#!/usr/bin/env python

import time
import SocketServer

class MockCgminerHandler(SocketServer.StreamRequestHandler):

    def handle(self):
        # self.rfile is a file-like object created by the handler;
        # we can now use e.g. readline() instead of raw recv() calls
        self.data = self.rfile.readline().strip()
        #print "{} wrote:".format(self.client_address[0])
        print 'Received: {}'.format(self.data)
        # Likewise, self.wfile is a file-like object used to write back
        # to the client
        self.wfile.write('MHS 5s=12345')

if __name__ == "__main__":
    HOST, PORT = "localhost", 4028

    server = SocketServer.TCPServer((HOST, PORT), MockCgminerHandler)

    # Activate the server; this will keep running until you
    # interrupt the program with Ctrl-C
    server.serve_forever()
